Use Web Workers and dynamically assign ports for concurrent scanning | 提升 128 倍扫描速度
MikeWang000000/ClashScan pull request #1
Opened 2024-09-29 05:28 UTC by zmaplex

2024-09-29 17:55 UTC, MikeWang000000 commented
感谢！我看并发增加到了64，后续的请求都有成功发送吗？

我在 Windows 平台 Chrome 测试中曾遇到 `net::INSUFFICIENT_RESOURCES` 的问题，导致后续 `fetch()` 实际上没有发出请求就直接失败了，降低后得以缓解，因此未敢将数值设定非常高。

Windows 平台上的 `fetch()` 比较低效，最长 2 秒左右才有结果。因此存在一定漏检的可能性。我测试了下您的网页，漏掉了我的 `8080` 端口。加大并发的时候，可能需要将超时也放宽一些（目前是 120 ms）。

2024-09-30 01:25 UTC, zmaplex commented
128 个并发确实会有概率漏检，改成 64 个 worker 工作的话目前测试没问题。

8080 端口这边没复现，可以检出。 可能是Windows或者浏览器版本或者环境的问题导致的

![image](https://github.com/user-attachments/assets/72e00587-872b-4dd6-8a98-21efc49ddfcb)

2024-09-30 02:25 UTC, MikeWang000000 commented
前面的路径问题可以解决一下吗？我在代码中标注出来了。

2024-09-30 02:58 UTC, zmaplex commented
前面的路径问题 指的是? 我没看到相关标注

另外我修复了之前代码 Bug 

**网络请求数= worker 数 * 端口数**  修正为 **网络请求数 = 端口数**

 现在多次测试 8080 端口均被检测到

2024-09-30 03:36 UTC, MikeWang000000 requested changes
路径问题需要修改。

2024-09-30 03:36 UTC, MikeWang000000 commented on index.html
> +    <link rel="manifest" href="/manifest.json">
普通仓库的 GitHub Pages 不以 `/` 起始，这里 404 了。

2024-09-30 03:36 UTC, MikeWang000000 commented on script.js
> +      navigator.serviceWorker.register('/service-worker.js')
同上

2024-09-30 03:43 UTC, MikeWang000000 commented
前面的代码review没有提交上，我重新标了一下。再看一下呢？

2024-09-30 04:05 UTC, zmaplex commented
感谢指出，路径问题已经解决了

2024-09-30 16:50 UTC, MikeWang000000 approved these changes
LGTM

2024-09-30 16:51 UTC, merged

2024-09-30 16:51 UTC, MikeWang000000 commented
Thanks!